### ISSUE TITLE
[Web-Interface] Dropdown of dynos is not sorted alphebetically

### ISSUE THREAD

**Issue by mobilutz** [judoscale/judoscale-ruby#115]
This is not `ruby` related but related to the Web-Interface.

The problem is, that the dyno list is not sorted alphabetically which makes it hard to find the correct dyno sometimes.
![Screenshot 2023-01-16 at 11 30 46](https://user-images.githubusercontent.com/491877/212657767-a584cce1-bae6-44d1-a78c-77fa8e078826.png)

Could you please add alphabetical-sorting everywhere - saying this because on the `edit dyno list` the sorting is different as well.

Thanks

**Comment by adamlogic** [comment]
Yes, I'll fix this today.

**Comment by adamlogic** [comment]
Fixed. Thanks for the report!

**Comment by mobilutz** [comment]
Thanks for the quick change, now it looks way better and things are easier to find.
