### ISSUE TITLE
`Judoscale::Reporter` doesn't always follow `Judoscale::Config.log_level`

### ISSUE THREAD

**Issue by azanar** [judoscale/judoscale-ruby#187]
## Expected

In `config/initializers/judoscale.rb`:

```
if defined?(Judoscale)
  Judoscale.configure do |config|
    config.log_level = :warn
  end
end
```

In logs: no `INFO` messages

## Actual

In logs:

```
INFO -- : [Judoscale] Reporting 40 metrics
```

## Workaround

```
if defined?(Judoscale)
  Judoscale.configure do |config|
    config.log_level = :warn
    Judoscale::Reporter.instance.logger.log_level = ::Logger::Severity::WARN
  end
end
```

## Analysis

There appears to be a race condition between `Judoscale::Config.instance` and `Judoscale::Reporter.instance.logger`.

When `Judoscale::Reporter.instance.logger` is called, that calls this code: https://github.com/judoscale/judoscale-ruby/blob/main/judoscale-ruby/lib/judoscale/logger.rb#L9

The first time that code is called, it takes `Judoscale::Config.instance.log_level` _at that moment_, and hands it to a new instance `LoggerProxy`. All later calls hand back the same instance of `LoggerProxy`. Any later changes to `Judoscale::Config.instance.log_level` won't be reflected.

The `Logger` instance wrapped by `LoggerProxy` has no log level set: https://github.com/judoscale/judoscale-ruby/blob/main/judoscale-ruby/lib/judoscale/config.rb#L83

## Potential Solutions

1. Assign and keep in sync `Judoscale::Config.instance.log_level` with `Judoscale::Config.instance.logger`
2. Update `Judoscale::Reporter.instance.logger` when `Judoscale::Config.instance.log_level` changes.

**Comment by adamlogic** [comment]
This is the best issue! Thanks so much for the clear repro steps, analysis, and potential solutions. 💯 

I'll do some testing and create a PR for this next week. 👍
