### ISSUE TITLE
Feature request: Redirect to the requested page on reauthorization

### ISSUE THREAD

**Issue by mobilutz** [judoscale/judoscale-ruby#32]
As we are now using RailsAutoScale on two production heroku apps, this case very often happens:

* go to (click) i.e. `Settings` on RailsAutoScale
* reauthorization happens - as I was using RailsAutoScale for another app
* multiple redirects and then I see the "root" page of the app I wanted to see `Settings` for
* need to click again on `Settings`

The idea/feature here is, to save the requested page before doing authorization and then redirecting to that page, and not the root page of RailsAutoScale.

This would really help me - and I guess other people as well - very very much.

Thanks for the great work BTW 😃

**Comment by adamlogic** [comment]
Thanks for pointing this out. I'll look into it.

**Comment by mobilutz** [comment]
Closing this, as now with judoscale this is not even possible anymore as the internal integer-ID (which usage is  not ideal, should better be UUID or something else) is in the URL. And therefore it is not possible to switch between judoscale configurations easily anymore 😦

**Comment by adamlogic** [comment]
I don't think I quite understand what you mean by "switch between configurations".

**Comment by mobilutz** [comment]
I am maintaining an application that has multiple heroku-instances (horizontal scaling) and each of them has judoscale attached to it.

With `rails-autoscaling` it was easily possible to switch between the judoscale configurations for each of the apps, as the heroku-app-name was the only part in the URL that changed. With judoscale, there is the integer-ID in the URL as well, and therefore one cannot just change the name of the heroku-app in the judoscale URL.


While writing this down, I found that it is hard to describe. Lets not talk about this more, as I don't think we need to 😉
