### ISSUE TITLE
Feature request: loosen Resque version requirement

### ISSUE THREAD

**Issue by latortuga** [judoscale/judoscale-ruby#52]
With the migration to the new gem suite, I cannot upgrade because the version of Resque stipulated by the new `-resque` gem is stricter (`>= 2.0`) than the old `_agent` gem (no version requirement). The functionality looks mostly unchanged to me, can you please loosen the requirement so that Resque 1.x is supported?

**Comment by adamlogic** [comment]
I'll take a look!

**Comment by latortuga** [comment]
I managed to move to Resque 2 so I'm closing this. Good luck and godspeed to anyone else stuck ~in hell~ on Resque 1!
