### ISSUE TITLE
Feature request: Support Shoryuken backend queue

### ISSUE THREAD

**Issue by fluke** [judoscale/judoscale-ruby#62]
In 2021, one of our customers, Pablo Cantero, [reached out about Shoryuken support](https://app.plain.com/workspace/w_01HV9NKTDM9F1MH8RGZBAF9BTT/thread/th_01HV9XD3FQTTH7V252BM3WG85X/?q=shoryuken). Shoryuken is a [Rails job processor for Amazon SQS](https://github.com/ruby-shoryuken/shoryuken).

I helped Pablo create his own custom adapter. He recently [reached out again](https://app.plain.com/workspace/w_01HV9NKTDM9F1MH8RGZBAF9BTT/thread/th_01HV9ZRZA101F4ZE864AG3121S/?q=shoryuken) because he recommended us to a friend who is also using Shoryuken. That friend is Denis Zgonjanin, who is now one our few ECS customers.

Denis [reached out separately](https://app.plain.com/workspace/w_01HV9NKTDM9F1MH8RGZBAF9BTT/thread/th_01HV9ZRVBXG5Q2JZXR82GQR4N5/?q=shoryuken) because he was having trouble getting [Pablo's custom adapter](https://gist.github.com/phstc/7d0682932f30d349dc0f3989b358109a) working. The problem was that the adapter reports *queue depth*, not *queue time*. By default, `process_type.metric` is "adapter_queue_time", and users cannot change it.

I changed it for him via prod console (`process_type.update! metric: "adapter_queue_depth"`), and now he's autoscaling [his SQS workers](https://app.judoscale.com/14109-DownpayComputeStack-DownpayFargateCluster19091FF1-qiwzKCsfrx9k/dynos/DownpayWorkerApp) via queue depth and a custom adapter:

<img src="https://uploads.linear.app/2fba0abb-1a66-4279-9c07-4dd0c012d1c1/22a233bc-544c-4650-b30b-83538742ad2d/d74ff4ab-f9a8-4561-bb99-476bbc195b1d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmYmEwYWJiLTFhNjYtNDI3OS05YzA3LTRkZDBjMDEyZDFjMS8yMmEyMzNiYy01NDRjLTQ2NTAtYjMwYi04MzUzODc0MmFkMmQvZDc0ZmY0YWItZjlhOC00NTYxLWJiOTktNDc2YmJjMTk1YjFkIiwiaWF0IjoxNzE0MjI2OTcwLCJleHAiOjMzMjg0Nzg2OTcwfQ.PairWae_1iVDzNbMsD4RabYb43lghtf8Ez_J0gdlQ7M " alt="CleanShot 2024-04-18 at 08.27.10@2x.png" width="2566" height="1478" />

We don't have a lot of customers asking for Shoryuken support, but Denis made a great point that we'll probably have more ECS customers using SQS. And since we already have [a Gist](https://gist.github.com/phstc/7d0682932f30d349dc0f3989b358109a) that's working for two customers, I'd love to bake in official support.

Two challenges:

* In order to manually test our own Shoryuken support, we'll need to run an SQS instances. 😬 Hopefully this isn't to much of a time sink.
* We either need to find a way to support queue time with Shoryuken, or we need to let our users change their metric from queue time to queue depth.

On the second point, [Pablos' research](https://app.plain.com/workspace/w_01HV9NKTDM9F1MH8RGZBAF9BTT/thread/th_01HVA9E7VZ66G4TR8EBW8867QF/?q=shoryuken) makes it sound like queue time will be problematic because SQS retries don't reset the enqueued time. We need to make sure that queue time for retried jobs are measured from when the job *reenters the queue*, not when it first entered the queue. Maybe we could do something like [we do for Resque](https://github.com/judoscale/judoscale-ruby/blob/main/judoscale-resque/lib/judoscale/resque/latency_extension.rb)?

If not, it won't be a dealbreaker to use queue depth. If Judoscale detects the presence of a queue depth metric—but no queue time—we could display a message and a button for the user to change their autoscale metric. We had something like this in the past, and it may still exist in the code.

*Note that there's also an old GitHub issue linked below. We should resolve that once we've added support for Shoryuken.*

**Comment by adamlogic** [comment]
Thanks for the request! Shoryuken is on our list to support, and I'm also working on a guide for creating a custom worker adapter.

**Comment by fluke** [comment]
Hey wanted to follow up on this. Been pretty much exactly a year and our needs have scaled. If it's still not yet up I'll consider working on this.

**Comment by adamlogic** [comment]
Thanks for the follow-up. We haven't seen much demand for Shoryuken support, so this hasn't made it to the top of our priority list yet.

We did write up a doc on [creating a custom adapter](https://judoscale.com/docs/custom-worker-ruby) that'll be helpful if you tackle this on your own.

**Comment by carlosantoniodasilva** [comment]
@fluke we just [released v1.7.0](https://github.com/judoscale/judoscale-ruby/releases/tag/v1.7.0) adding initial support for Shoryuken, let us know how that works for you or if you run into any trouble, we'll be happy to help. Thanks!
