### ISSUE TITLE
Broken for Rails application using Log4r

### ISSUE THREAD

**Issue by boof** [judoscale/judoscale-ruby#68]
The new method of using a logger proxy internally expecting "#add(...)" to accept messages breaks Rails applications at boot time when the application is configured to log via an instance of Log4r.

Log4r "#add(outputter)" method expects an instance of Outputter and raises when `outputter` is not a Outputter.

## Workaround
To circumvent this problem we currently disabled automatic loading of the gem (via Gemfile `require: false`) to load it later in the `rails_autoscale.rb` initializer.

In there we define a Log4rAdapter class that just delegates the `add` calls to their severity named counterparts initialize the logger and the rack middleware manually.

## Solution
Long-Term I suggest not relying on the `#add` method but instead use `public_send(method_name = severity_name.downcase)`.

It seems you want to ensure these RailsAutoscale loglines are always emitted when log_level is configured. I am unsure why this behaviour was implemented either way.

---

Don't know if this is intentional, but FATAL is missing in https://github.com/rails-autoscale/rails-autoscale-gems/blob/87bb3342c9c2600ca39cc56dbade4ae13d81477f/rails-autoscale-core/lib/rails_autoscale/logger.rb#L14

**Comment by adamlogic** [comment]
@boof Thanks for reporting this.

> Long-Term I suggest not relying on the `#add` method but instead use `public_send(method_name = severity_name.downcase)`.

I think I agree with you here. I'll test it out.

> It seems you want to ensure these RailsAutoscale loglines are always emitted when log_level is configured. I am unsure why this behaviour was implemented either way.

The proxy allows users to override the log_level only for logs emitted from the gem, not impacting the underlying logger.

> Don't know if this is intentional, but FATAL is missing

Not intentional. Thanks for calling it out.

**Comment by adamlogic** [comment]
@boof Fixed in main. Planning a gem release later today.

**Comment by boof** [comment]
Thank you! 👍
