### ISSUE TITLE
rails-autoscale-web/sidekiq >= 1.2 does not report any data

### ISSUE THREAD

**Issue by mobilutz** [judoscale/judoscale-ruby#84]
We just updated the gems from < 1.2 to 1.2.1 and there is no more reporting happening from our heroku apps to judoscale.

Unfortunately, I have not found anything in the logs (we are currently having a log flood), so there is no more information I can guess.

We will be downgrading, to see if it resolves the issue and then I will check if I can provide more information.

**Comment by jon-sully** [comment]
Greetings @mobilutz 👋 

Thanks so much for the report. We'll do what we can on our end to see what's happening (we released the new version and made some back-end changes yesterday) but any additional info you could provide would indeed be quite helpful. We definitely want to make sure your metrics make it to Judoscale!

**Comment by mobilutz** [comment]
So far I can see, that there is no log regarding active scaling in our logs.

So things like `[RailsAutoscale] Reporter starting,` are not showing for the v1.2.1 version 😦 

But as I said, I will provide more info when I have them.

**Comment by jon-sully** [comment]
Interesting! Could you check to see if any logging output is using the `Judoscale` moniker as well / instead of `RailsAutoscale`?

**Comment by mobilutz** [comment]
> Interesting! Could you check to see if any logging output is using the `Judoscale` moniker as well / instead of `RailsAutoscale`?

I just used grep with `scale`, so should have seen `Judoscale` there.

Like I said, will downgrade for now, and then in the next days dig into this.

As [changes](https://github.com/judoscale/judoscale-ruby/compare/v1.1.1...v1.2.1) between the version are mostly naming related, I think we (in our deployment process) have a caching issue I think.

**Comment by jon-sully** [comment]
Gotcha. Well certainly don't rush on our behalf but we're ready to help if you find more details in the coming days 👍

**Comment by mobilutz** [comment]
@jon-sully Now I have some more information.

I finally got downscaling working, the problem was that even when setting `rails-autoscale-web` and `rails-autoscale-sidekiq` to `v1.1.1` there was still `rails-autoscale-core` at `v1.2.1`

Could you guys please create a new release `1.1.2` for every repo, that forces `rails-autoscale-core` to <1.2?


And now I also finally have a reviewapp running with `rails-autoscale-xxx` with `v1.2.1`. Which was unfortunately not as easy as I thought, and I have a problem that `sidekiq` metrics are not send to judoscale 😦 

I am a bit disappointed to be honest, that the name change was not inside a `major` version change, but inside a `minor` version change 😦 


How I will proceed now, I will try to first solve the issue of no `sidekiq` reporting in `judoscale` `v1.2.1` and when I have this working, I maybe will try to setup a test application showing my issue.

**Comment by mobilutz** [comment]
Ok, I should have waited a bit more than 1 minute after the rails app ran.

I am now seeing content from sidekiq in the judoscale app!

I was just not patient enough, as I was a bit frustrated because it took me almost 4 hours to get to the point I am at now 😦

**Comment by mobilutz** [comment]
@jon-sully As said just 21 minutes ago, the upgrade to `judoscale` `v1.2.1` was working. I needed to change some things in regards of `judoscale-web` - for which I created a new issue: https://github.com/judoscale/judoscale-ruby/issues/86

I will close this now, but I would really urge you to tackle this:
> Could you guys please create a new release 1.1.2 for every repo, that forces rails-autoscale-core to <1.2?

**Comment by adamlogic** [comment]
> Could you guys please create a new release 1.1.2 for every repo, that forces rails-autoscale-core to <1.2?

I think I've captured this in #87. LMK if there's more to it that I'm missing.

**Comment by mobilutz** [comment]
> I think I've captured this in #87. LMK if there's more to it that I'm missing.

Hi @adamlogic, yes this looks good to me.

The thing I would make sure here is that any adapter (is that the right name) `<1.2` will not install anything with the new naming scheme. So `rails-autoscale-core` should definately be limited to `<1.2`
