### ISSUE TITLE
Documentation outdated with v1.2.1

### ISSUE THREAD

**Issue by mobilutz** [judoscale/judoscale-ruby#86]
The addon-name change leads to some things still not completely correct.

In the [Rails Installation section](https://judoscale.com/docs/installation-rails) the following things needs to be updated:

1. screenshots still show `rails-autoscale-xxx`
2. in `Manual Install` there is `judoscale-web` listed, which as far as I see should be `judoscale-rails`

I know that a renaming is not easy and there are always things that will not be correct. So this is why I am just trying to support here.

**Comment by adamlogic** [comment]
@mobilutz Thanks for pointing these out! We're on it. 👍

**Comment by adamlogic** [comment]
- [ ] screenshots still show rails-autoscale-xxx
- [x] in Manual Install there is judoscale-web listed, which as far as I see should be judoscale-rails

**Comment by mobilutz** [comment]
@adamlogic It seems that the screenshots have been changes.

I will close this then. Thanks
